### ISSUE TITLE
What should helper do if an `AggregateShareReq` references incomplete aggregate jobs?

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#104]
A question I encountered while implementing the helper's `/aggregate_share`:

```
What should we do if any of the aggregation jobs handling reports relevant to
the aggregate share request aren't finished yet? Helper could return an error like
"EAGAIN" to leader, or could trust leader not to issue an AggregateShareReq until all of
leader's aggregate jobs are done (which should imply that helper's are done).
```

[Discussion thread from PR #103](https://github.com/divviup/janus/pull/103/files#r858994569)

**Comment by tgeoghegan** [comment]
I think the helper has to allow some aggregate jobs to be abandoned. Consider the case where the leader constructs an aggregate job and sends `AggregateInitReq` to helper for it. The helper successfully services that request but sends an `AggregateResp` whose `Transition`s are out of order. The leader will abort that particular aggregation job, which means the helper will never get an `AggregateContinueReq` for it and the aggregate job will remain forever incomplete in the helper's datastore. The leader may then wish to send an `AggregateShareReq` covering a batch interval that includes the abandoned aggregate job (perhaps there were many other aggregate jobs in that interval that leader and helper handled successfully). We should allow helper to service that `AggregateShareReq`.

**Comment by cjpatton** [comment]
FWIW that's the behavior I went with. We may want to do something about this in the spec at some point.

**Comment by tgeoghegan** [comment]
So we agree that helper has to accept that the leader might abandon some aggregation jobs. But we should also be mindful of the case where an `AggregateShareReq` comes in while the helper (or another replica of the helper!) is still handling an `AggregateContinueReq` that pertains to the `AggregateShareReq`. The leader really shouldn't be sending `AggregateShareReq` until it knows the helper is done handling the relevant aggregation jobs (how could the leader compute the expected checksum and report count until it knows what reports the helper has accepted?) but we could make sure that our DB transactions are set up such that handling of an `AggregateShareReq` blocks until the `AggregateContinueReq`s have been handled.

**Comment by BranLwyd** [comment]
IMO we should lean on database serialization here: with how Janus' datastore works, if the `AggregateShareReq`'s database transaction is running concurrently with `AggregateContinueReq`'s database transaction, one of these transactions will succeed while one will be restarted (since they will inherently conflict with one another). If the `AggregateContinueReq` goes before the `AggregateShareReq`, its output shares will be included in the aggregate share (assuming they completed); if the `AggregateContinueReq` goes after the `AggregateShareReq`, it will fail due to being an aggregation attempt on a batch unit that has already started collection [1].

It's not inherent that an implementation would necessarily work this way, even with database serialization--for example, if we implemented things with multiple DB transactions, DB serialization wouldn't necessarily help. IMO we should check & maintain these semantics in our implementation.

[1] Actually, I couldn't find anything in the specification text that either the leader shouldn't create aggregation jobs for batch units that have started the aggregation share process, nor that a helper shouldn't process an aggregate init/continue for batch units that have already been shared out. If I'm not missing something, perhaps we should clarify the spec here?

**Comment by divergentdave** [comment]
Section 4.3.1.4, "Input Share Validation" does include checks that individual reports haven't already been included in an aggregation job and that they aren't contained by any batches that have already been collected. This is referenced in two places, before the leader sends an AggregateInitReq, and after the helper receives an AggregateInitReq. We may want to add a requirement that the helper also does similar checks on receipt of an AggregateContinueReq.

**Comment by BranLwyd** [comment]
Ah, thanks -- my view was of the interop pilot branch, it looks like a check was added to the main branch but not ported to the interop branch.

I agree we should do these checks on continuing aggregation, as well as at initialization time -- otherwise a leader could finish an aggregation that was started before collection, which would change the results.

**Comment by tgeoghegan** [comment]
Relevant issue on the protocol: https://github.com/ietf-wg-ppm/ppm-specification/issues/241

**Comment by tgeoghegan** [comment]
We since have made spec changes that require the leader to drive agg jobs to completion before sending aggregate share requests, so I think this is outdated.
