### ISSUE TITLE
Immutability of SQL migration scripts

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1252]
The Janus sources now include a series of SQL migration scripts in `db`. However, the series of migrations isn't just a property of a single git commit independent of all other context. Specifically, it should only be possible to change the state of migrations by appending a new migration to the end of the list, because we can't rewrite the history of migrations applied to deployed environments.

Currently, Janus' `publish-sql-schema` workflow simply copies all of `janus/db` into a directory like `gs://janus-artifacts-sql-schemas/0.x`, overwriting whatever was there before. That workflow and `ci-build` should verify that:

- any existing migration scripts have not been changed
- no migration scripts are inserted anywhere except the end of the sequence
- no migration scripts are removed

**Comment by inahga** [comment]
I was able to create a CI script that checks each PR for validity of the migration scripts. https://github.com/divviup/janus/pull/1442.

---

As for validation on the deploy-side, here's the strategy I lean towards:
- Compare the new schema to the last released version (i.e. diff'ing between the two git tags). If the schema is OK, upload the new schema UNLESS the GCS bucket already has stuff in it.
- If there is stuff in the GCS bucket, that means that a schema was already uploaded and this build is probably being run as `workflow_dispatch`. In this case, fail the build, UNLESS a `force` option was provided. 
- If `force` was provided, and the schema is valid, go ahead and upload the schema, overwriting what is in there.

I leave the `force` escape hatch open in case there was some error that caused the original release build to fail to upload its schema part-way through, or if we otherwise know what we're doing.

For point 1, the logic from #1442 can be used, possibly via [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

**Comment by inahga** [comment]
I've done a final test of all the changes, but it's not possible to fully test the `publish schema` workflow as it will only deploy from tags, and there is no available tag that has the newly updated workflow. I've tested it thoroughly in isolation, but the final word will have to come from on-call next week. I'll close and re-open if necessary then.
