### ISSUE TITLE
Space optimization: don't store output shares

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1284]
One possible time/space tradeoff we could make is to stop storing Prio3 output shares on disk. With a very large Prio3 instance, most of the helper's storage usage comes from output shares, as all other per-report messages are very small. The `report_aggregations.out_share` column could be deleted, and the output share could be re-derived from the seed in the helper share as needed, using the PRG. (in the leader's case, output shares can be recomputed by truncating the input share) Then, aggregation share accumulators could be updated with those in-memory output shares. However, this may require reaching through the VDAF abstraction layer to accomplish.

**Comment by branlwyd** [comment]
Rather than a VDAF-specific change, I think we should consider dropping the `report_aggregations.out_share` column entirely (that is, stop recording output shares).

Both Leader & Helper will accumulate any completed aggregations into the `batch_aggregations` table, and the `batch_aggregations` table is used to process collection requests -- nothing ever reads `out_share` once it is written.
