### ISSUE TITLE
Parallelize iterators where possible (and sensible)

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1307]
There's a number of places throughout Janus where we iterate over a potentially long list of reports, or report aggregations, or aggregation jobs, or whatever, and do some work that can be parallelized. Sometimes this is compute-bound VDAF work, sometimes this is database queries. We should look into parallelizing these, either by spawning `tokio` tasks and using `try_join_all` as in https://github.com/divviup/janus/pull/1305, or by using [`rayon` parallel iterators](https://docs.rs/rayon/latest/rayon/iter/index.html).

**Comment by tgeoghegan** [comment]
If we're keeping multiple threads busy doing VDAF math, we probably want to revisit Kubernetes resource requests/limits we set on Janus deployments.

**Comment by branlwyd** [comment]
Agreed with IO (like DB interactions) -- we should be running IO operations using as much parallelism as possible, so that we can take advantage of e.g. Postgres' pipelining & reduce the number of effective network round-trips required to complete operations.

Parallelizing CPU work is less clear; in many cases, work is already parallelized. For example, aggregation jobs can currently be processed in parallel; even if the VDAF computations are done serially, aggregation job processing can happen over many aggregation jobs at once, effectively allowing parallelization of aggregation computations (across different aggregation jobs) already. In this case, aggregation job processing is "embarrassingly parallel" in the sense that the parallel operations do not have synchronization overhead [other than IO throughput as a bottleneck, probably]. I suspect there is at least a small amount of synchronization overhead in using `rayon`, so we might actually decrease throughput by parallelizing VDAF computations. Even if there isn't a synchronization overhead, we might effectively be making a tradeoff of "handle a relatively large number of aggregation jobs, relatively slowly" with serial VDAF computations to "handle a relatively small number of aggregation jobs, relatively quickly" with parallel VDAF operations.

All of which is not to say that we can't try this -- I would just suggest that we benchmark to make sure this is effectively a win, in a realistic deployment scenario (i.e. with enough aggregation jobs available to saturate the cores under test for the serial case).

In all cases, we should focus on updating mainline application code rather than test code. (not that there's anything wrong with parallelizing test code, it is just less valuable to do so IMO)

**Comment by branlwyd** [comment]
This is done for aggregation; I think we can close this. If we run into performance issues in other places we iterate, we can consider parallelization.
