### ISSUE TITLE
Should the aggregation job creator use leases?

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1365]
Scaling the aggregation job creator has been an open issue for a while now. Currently, it discovers unaggregated reports using a `FOR UPDATE SKIP LOCKED` query over client reports with `aggregation_started = FALSE`. This is done on a repeating basis for all DAP tasks. Before the introduction of the `FOR UPDATE SKIP LOCKED`, when we were using the SERIALIZABLE isolation level running more than one of these would have led to more rollbacks as they fought over reports. Following #1354, these transactions will also update the `batches` table, which will lead to more conflicting writes and rollbacks.

We could coordinate the activity of multiple aggregation job creators to avoid this contention if we had per-DAP task leases for aggregation job creation. This could work similarly to how our job drivers acquire leases, except we may want a dedicated table for aggregation job creation leases. We'd probably want to choose which tasks to check based on when the aggregation job creator last ran for each task. (since each lease row will stick around until the task is decommissioned, and the 'job' of job creation never reaches a terminal state)

**Comment by branlwyd** [comment]
Leases would work to resolve contention here. But effectively we'd be getting contending behavior either way -- aggregation job creators would contend over the per-task lease rather than report rows. Of course, we might be saving effort by having the contention be over a relatively cheap "acquire lease" operation rather than acquire reports + group reports in-memory + write report groupings as aggregation jobs operation -- but I suspect the in-memory grouping logic itself is pretty cheap (no tricky VDAF operations, effectively just "chunking" the set of reports that are available). Avoiding transmission of the aggregation jobs to write might help if we are getting that far before incurring a restart.

Another option we've discussed would be to shard the set of tasks being worked on per aggregation job creator to appropriately limit contention. e.g. something like: cohort A of job creators handles this range of task IDs, cohort B of job creators handles this range of task IDs, etc. Aggregation job creators within a cohort will contend for reports in their tasks, but no contention will exist between aggregation job creators in different cohorts.

**Comment by branlwyd** [comment]
We have considerably reduced the potential for contention here: all batch metadata is now "sharded" across multiple rows, so two writes only contend if they happen to touch the same "shard". I think `FOR UPDATE SKIP LOCKED` on acquiring unaggregated reports is good enough to solve contention on grabbing reports.

If that isn't good enough, I think we would "shard" the aggregation job creator such that one (or a few) agg job creator replicas are responsible for creating aggregation jobs for a given range of task IDs.
