### ISSUE TITLE
Best practice for initializing db for janus with sqlx-cli

### ISSUE THREAD

**Issue by MxmUrw** [divviup/janus#1391]
Hi!

As described in the [documentation for deployment](https://github.com/dpsa-project/janus/blob/main/docs/DEPLOYING.md), `sqlx-cli` has to be used to apply all migrations in the `db` folder to a fresh postgres database. I have a question with regards to how this could be done in the context of a `docker-compose.yml` file.

Previously, we could start a local janus instance (with databases and 2 aggregation servers) using a [single `docker-compose` file](https://github.com/dpsa-project/dpsa4fl-infrastructure/blob/main/local-docker-setup/docker-compose.yml). This was possible because the standard `postgres` docker container image could be initialized with the single `schema.sql` file that was previously available for janus. Now that the additional `sqlx-cli` executable is required, it is unclear to me how a `docker-compose` setup might look like.

My initial guess is that I want to build an additional container image containing the `sqlx-cli` executable and running the `sqlx-cli migrate run` command. This would be part of my compose file, and by setting explicit dependencies between the containers things should run in the correct order.

Nevertheless, this seems like an unelegant solution, in particular since building an image for the sole purpose of initializing a database seems like overkill. Are there easier ways to achieve a setup where running a single command like `docker-compose up` would setup both databases and also janus? Is the best solution to split database setup and janus setup into two compose files?

I realize that this question might not be directly relevant to janus development, though I'm asking in the hope of someone more experienced having some intuition for what would be the best way to proceed for me. Thanks!

**Comment by tgeoghegan** [comment]
Running another container that runs `sqlx migrate run` is indeed how we handle this in our integration test setup, which uses [Kind](https://kind.sigs.k8s.io). I'm not intimately familiar with `docker-compose`, but I would hope something similar is possible there.

You might have some luck using the interop aggregator image. It's designed for ephemeral tests and is already set up to [apply migrations at startup](https://github.com/divviup/janus/blob/d8498abfed766f6824b0fee865d925d6d4f87b92/interop_binaries/src/bin/janus_interop_aggregator.rs#L216).

An alternative would be to adapt the stuff in `janus_aggregator_core::datastore::test_util` that applies migrations ([link](https://github.com/divviup/janus/blob/d8498abfed766f6824b0fee865d925d6d4f87b92/aggregator_core/src/datastore/test_util.rs#L137)) so that it's usable outside of test configs. We deliberately _don't_ do this in Janus because we don't want to apply migrations at startup (sequencing code deploys and schema migrations in persistent deployments is not that easy), but it sounds like it could be what you want.

**Comment by MxmUrw** [comment]
Ok, I see. I will look into those options.

Thanks for the answer!

**Comment by tgeoghegan** [comment]
I want to reopen this for now, to ask my colleagues @branlwyd and @divergentdave what they think about this.

Maxim and Olivia are not be the only people out there who will want to be able to easily run disposable instances of Janus without having to worry about DB migrations. I wonder if we should add a config option to `janus_aggregator` that takes the path to a directory with migrations in it and uses `sqlx::migrate::Migrator` at startup to apply them. We still don't want to use that in Divvi Up, but it might spare teams experimenting with Janus some `docker-compose` chores.

**Comment by branlwyd** [comment]
I'd prefer we didn't build DB-migration logic into the normal `aggregator` binary.

The fastest course forward for testing purposes is likely David's suggestion to concatenate the migration files into a single schema, and use that where `schema.sql` would have been used before. (I'm not sure we have good advice for a production deployment case; we built our own DB-migration infrastructure based on GitHub actions.)

**Comment by MxmUrw** [comment]
> One other strategy: the migration scripts are all plain SQL, so concatenating `db/*.up.sql` in numeric order would give you a schema file suitable for use as an initialization script.

I think it's worth putting this sentence into the `DEPLOYING.md`, as knowing this would have been enough in my case. As it is now, I already setup a dedicated container for running `sqlx` with docker-compose as Tim suggested - which works equally well.
