### ISSUE TITLE
Bug: redundant task queries at high QPS

### ISSUE THREAD

**Issue by inahga** [divviup/janus#1639]
In function `task_aggregator_for()`, there is a mutex that is acquired twice. In between those locks, a database transaction occurs. In theory, multiple requests *could* enter the database transaction at a time, resulting in redundant queries. See https://github.com/divviup/janus/blob/2914a68ad09c8f30229f3a5eb9b4055b97608c7f/aggregator/src/aggregator.rs#L428.

At the moment, this isn't a big deal since this cache never invalidates AND we have to be experiencing a period of high QPS when the cache is being loaded. However, if we [implement an invalidation strategy for this cache](https://github.com/divviup/janus/issues/238), this problem becomes more severe.

**Comment by inahga** [comment]
There's not really any way around this that doesn't involve holding a lock during a database operation, which we'd prefer to avoid.

**Comment by branlwyd** [comment]
I'm fine not solving this, but one potential solution would be to make the cache store something morally equivalent to a `OnceLock<Arc<TaskAggregator>>` for each task (except I think not a OnceLock, specifically, since it wouldn't be able to handle errors in the DB transaction appropriately).

Then `task_aggregator_for` would look something like:
1. First, lock the `task_aggregators` mutex, and retrieve the existing `OnceLock` for the task. If there is no existing entry, write a new empty `OnceLock` for this task. Release the `task_aggregators` mutex.
2. Do (pseudocode) `OnceLock.get_or_init(|| retrieve_task_from_db(task_id))` to retrieve the task and return it.

(an actual implementation might use a second `Mutex` instead of a `OnceLock`, which would allow us to handle the case of an error in the DB transaction appropriately. one solution to errors would be to return it immediately, so that the next caller gets their own chance to read from the DB successfully.)

In this design, the lock over the cache would be held only briefly (during step 1). Multiple callers trying to retrieve the same task would contend over the task's `OnceLock`, but that is desirable to avoid multiple retrievals of the task from the DB. Cross-task contention would exist only briefly during step 1.

**Comment by branlwyd** [comment]
I have been nerd-sniped, I think I can fix this in a few minutes.
