### ISSUE TITLE
Better error when collection can't be created due to insufficient prepared reports

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1860]
If a Collector tries to create a collection _after_ a sufficient number of uploads have happened but _before_ Janus asynchronously schedules and runs the relevant aggregation jobs, then `collect` yields this error:

```
collect --task-id <snip> --leader 'https://dap-04.api.divviup.org/' --vdaf count --current-batch`
Error: HTTP response status 400 Bad Request - The batch implied by the query is invalid.
```

This isn't very helpful. The query is actually perfectly valid, it's just that the reports that it captures aren't aggregated yet. Janus should be able to distinguish the case from the one where not enough reports have been uploaded (we have the `client_reports` and `report_aggregations` rows, they're just in the wrong state), so we should be able to provide a better error and even a suggestion of what to do: try again in a few minutes after the next time `aggregation_job_{creator,driver}` runs. We could even make Janus aware of the scheduling parameters for the `aggregation_job_*` components so that it could provide a corresponding `Retry-After` header.

A related case is where the Collector tries to collect before enough reports have been uploaded. In that case, there's no way to provide a useful `Retry-After` -- Janus has no idea when uploads will happen -- but at least the error could specifically explain that there aren't enough uploaded reports rather than the broad "query is invalid".

**Comment by divergentdave** [comment]
#989 is related, but I vaguely recall we had a previous conversation somewhere else about spec interpretation on this point.

We could provide this additional guidance in the "detail" field of the problem details response, and then have the CLI print that as well.

**Comment by branlwyd** [comment]
This is indeed confusing, but I think that the behavior in Janus could be changed such that this error goes away entirely (as well as the related error regarding attempting to collect before enough reports are uploaded).

Currently, upon receipt of a collection job creation request with a `current-batch` query, Janus will greedily attempt to select a batch which has not yet been collected & which has enough reports associated with it (via aggregation job creation) to allow collection. If no such batch is available, we terminate the request with the error in the OP.

Instead, we could accept this request, noting that it is a `current-batch` request. Then, when we attempt to step the collection job, one of the first steps would be to select a specific batch ID for this collection job to collect. That is, we would _lazily_ select a specific batch to collect for each `current-batch` collection job. This would allow the Collector to issue requests at their leisure, and then poll them until they complete -- delays due to report uploads & aggregation job creation delays would effectively be hidden inside the polling process.

Thoughts? I think this is worth changing as it would simplify things for the Collector & remove an unnecessary error condition; it is also consistent with the DAP spec (AFAICT). We would need to move some of the collection job validation from "collection job creation" to "collection job step", at least for current-batch queries (since it is based on the specific batch being collected, which will no longer be determined until the collection job is stepped) -- this is allowed by DAP, as validation at time of collection job creation is a `MAY`. I think backporting to a version where we need to maintain backwards compatibility may be challenging, but I'll investigate that further as I implement.

**Comment by branlwyd** [comment]
(taking this issue to investigate implementation of https://github.com/divviup/janus/issues/1860#issuecomment-1699992694; if there are error messages to be improved as well w/ that change in place, I'll address those while I'm at it.)

**Comment by branlwyd** [comment]
Removing assignment from myself for now -- the suggested behavioral change to Janus turned out to be even more disruptive than expected.

**Comment by branlwyd** [comment]
This is a dup of #989 (modulo the solution discussion which did not work out).
