### ISSUE TITLE
`collect` output prints `std::time::Duration` in ISO 8601 and it looks funny

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1861]
`collect` prints the spanned interval when it displays collection results. That invokes the `Display` impl on `std::time::Duration` which outputs lines like:

`Spanned interval: start: 2023-08-30 15:24:00 UTC length: PT3960S`

I'm not sure if that's very good. Perhaps we should just print something like `3960 seconds`. Then again, we'd have to be cautious about breaking the API of the tool's output.

**Comment by divergentdave** [comment]
One correction: the above comes from `time::Duration`. `std::time::Duration` does not implement `Display`, see this [note](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#formatting-duration-values).

`<std::time::Duration as Debug>` would be less baroque: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0e5c67cf0c205febc8e4ff8643dec9e2

**Comment by branlwyd** [comment]
One other thought for discussion: maybe instead of a formatting of (start time, duration), the output format should be a formatting of (start time, end time)? I suspect folks will care about the start and end times more than the duration.

> Then again, we'd have to be cautious about breaking the API of the tool's output.

IMO, this tool's output is not intended for programmatic consumption, and therefore changing its output format should not be considered a backwards-compatibility break. (if we want folks to use this tool as part of Real Workflows, we should likely decide on a record format using a programmatically-consumable format such as JSON or YAML -- and consider changing _that_ format to be a backwards-compatiblity break)
