### ISSUE TITLE
Deal with `Prio3SumVec` and `Prio3Histogram` chunk length parameters

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1900]
In VDAF-07, `Prio3SumVec` and `Prio3Histogram` are parameterized by a chunk length for the underlying `ParallelSum` gadget. There is [some guidance on how to tune that value](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-07#name-selection-of-parallelsum-ch), but the conclusion is that a DAP implementation like Janus can't simply compute a good value.

For now, we are using the square root of the measurement size, which VDAF-07 says will give us non-optimal but not terrible proof lengths. Janus' representation of these VDAFs will have to account for chunk size so that divviup-api or a peer aggregator can instruct us what chunk size to use.

**Comment by branlwyd** [comment]
Janus should certainly represent chunk lengths directly in its VDAF representations (e.g. `VdafInstance`), as this parameter needs to match between the two aggregators.

But I think this is something that Divvi Up should hide from the user, and compute a reasonable value for, in any contexts we can. I think that means when we're the Leader.

> Setting chunk_length equal to the square root of the appropriate measurement length will result in proofs up to 50% larger than the optimal proof size.

This is worrying, as it somewhat hinders our ability to choose this value automatically. Is this something we could compute, either analytically with additional effort, or perhaps via guess-and-check on proof length? (would we be able to use optimization algorithms intended to find local minima, perhaps? we'd probably want to store the result once we it for any given measurement size.)

**Comment by divergentdave** [comment]
I've updated my [notebook](https://gist.github.com/divergentdave/a89fccd6375d9ac3d03cf5571709862d) with some more explorations. Here are a few new tidbits:

* The number of gadget calls for an optimal proof length jumps from $2^n$ to $2^{n+1}$ whenever we see the optimal chunk size drop sharply as length increases.
* In between the sharp drops, the optimal chunk size increases in a regular stair-step pattern.
  * For measurement lengths between 3 and 18, the optimal chunk size increases by +1 for every +3 measurement length.
  * For measurement lengths between 19 and 98, the optimal chunk size increases by +1 for every +7 measurement length.
  * For measurement lengths between 99 and 450, the optimal chunk size increases by +1 for every +15 measurement length.
* We can cast this optimization problem as a nonlinear integer programming problem.
  * Let the independent variables be the chunk size and number of gadget calls.
  * The (padded) measurement length is equal to the product of the chunk size and the number of gadget calls. For some fixed desired measurement length, we impose an inequality that this product is greater than or equal to our desired value, and we get a y=1/x-shaped boundary.
  * The proof length is also a function of the chunk size and number of gadget calls. While it is nonlinear, it happens to be a piecewise linear function. The domain is divided into several bands of interconnected almost-rectangular shapes, each of which has a slight horizontal gradient across it.
  * The horizontal gradient is due to the total arity component of the proof length, while the large discontinuities between regions are due to the gadget polynomial length, because the wire polynomial degree gets rounded up to the next power of two.

Integer programming and nonlinear programming are both hard categories of problems, but we may be able to do a fairly efficient search, say, by exhaustively checking which next-power-of-two regions are inside our boundary condition.

**Comment by divergentdave** [comment]
How embarassing, I was fooled by contour plot artifacts. Plotting a color mesh shows the only discontinuities are on horizontal lines (i.e. with the number of gadget calls fixed and the chunk length varying). This means we can limit our search to a few parameter choices near each (easy to find) intersection of the 1/x-shaped measurement length boundary condition and the gadget polynomial length discontinuities.

![image](https://github.com/divviup/janus/assets/181772/705b3a4e-fe6c-4581-9780-08afde0260cd)

![image](https://github.com/divviup/janus/assets/181772/d79a2238-eb09-4883-a58e-fd9cd053088b)
