### ISSUE TITLE
Janus and divviup-api should allow configuring report expiry

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2217]
The aggregator API on Janus allows specifying a task expiration, and this parameter is wired up through divviup-api's programmatic and console interfaces. However, we [hard code the _report_ expiry to two weeks](https://github.com/divviup/janus/blob/b175423c90c847df387a20746c2661b022fdee65/aggregator_api/src/routes.rs#L166). The aggregator API and Divvi Up should allow task authors to set this parameter per ask, and then Divvi Up should ensure it is provisioned into both aggregators appropriately.

**Comment by branlwyd** [comment]
We should be careful with this: report expiry effectively determines how long we store data, which impacts e.g. how long aggregates are available for collection. We don't want to store data too long, so that our storage costs don't grow too high. But we don't (plan to) reduce prices for subscribers who choose to lower this, so I'm not sure subscribers have an incentive to lower this from whatever maximum we choose -- they'd be lowering the amount of time they can collect data for no benefit to themselves.

We discussed that one partner might want to shorten this for data-retention policy reasons. But our default of 2 weeks was already within that policy. IMO, I'd like it if our policy was:

* Shared-service subscribers get a systemwide default report expiry time, i.e. 2 weeks currently. This is posted somewhere in our documentation.
* White-glove subscribers may negotiate a different limit, but we can configure their environment appropriately.

Thoughts? If this sounds good, I think we want to make this configurable at the deployment level, but not necessarily allow it to be configured for an individual task via the API.

**Comment by branlwyd** [comment]
Closing as not-planned for now. I still think that, in a shared-service context, every task should get a default report expiry age; and that in a white-glove context, we would configure expiry manually based on a request from the subscriber.

We _might_ eventually implement support for shortening the report expiry age even in a shared-service context, but I do not think we plan to implement this in the foreseeable future.
