### ISSUE TITLE
v0.6.2 requires setting database.tls_trust_store_path

### ISSUE THREAD

**Issue by jbuck** [divviup/janus#2226]
Hi there, I was testing out https://github.com/divviup/janus/commit/f85c31cab60681267190e34e15c17a46195ed36e in v0.6.2 and I found that if I deployed without setting `database.tls_trust_store_path` janus would exit with the following error:
```
Starting up
Error: couldn't create database connection pool Caused by:
0: couldn't make connection to database
1: Error occurred while creating a new object: error performing TLS handshake: invalid peer certificate: UnknownIssuer
2: error performing TLS handshake: invalid peer certificate: UnknownIssuer
3: invalid peer certificate: UnknownIssuer
```
Looking at the code adding this feature, it will always connect via TLS. Without setting the `tls_trust_store_path` parameter it'll load an empty root CA store, which I think means no certificate will ever work?

**Comment by divergentdave** [comment]
Note that the `NoTls` struct, which this commit replaced, always returned an error when it was used to create a TLS connection. I see that `tokio-postgres`'s configuration defaults to `SslMode::Prefer`, but there is special treatment for `NoTls` only that skips trying to connect with TLS if `SslMode::Prefer` and `NoTls` are used together. Given this, I think it would make sense to skip setting up rustls if `tls_trust_store_path` is not provided. This would give us back the default behavior from before, regardless of the behavior of the server. The unit tests are connecting to Postgres in a Docker container, and we have deployed v0.6.2 connecting to cloud-sql-proxy. In both cases, the server must be refusing TLS connection attempts, which leads to the client falling back to the unencrypted protocol. Presumably you are connecting directly to a Postgres instance which has a certificate and key set up, and thus the TLS connection attempt succeeds at the Postgres protocol level, so that the client takes the TLS handshake codepath, and ultimately fails.

**Comment by jbuck** [comment]
Ahhhh, that makes sense! Yes our CloudSQL instance has a server certificate generated (I think by default?) so it has TLS available
