### ISSUE TITLE
Performance and load testing

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#224]
Devise and execute a plan for measuring and analyzing performance of `janus_server`. This will require a lot of instrumentation so we can get detailed breakdowns of where we spend our time while preparing or aggregating reports. We will also have to devise means of generating adequate volumes of representative data.

**Comment by BranLwyd** [comment]
Note: I'm going through and converting TODOs to issues. I'm leaving the TODOs, but now with references to the underlying issues. Many performance-related TODOs now point at this issue.

**Comment by branlwyd** [comment]
One tactical performance-improvement idea from @tgeoghegan: introduce bulk database operations which read/write multiple rows in a single query, to replace locations where we currently pipeline multiple individual requests.

We chose to use pipelined-individual-requests because we believe the performance/resource difference is marginal, and writing single-row operations is simpler than writing both single-row & bulk operations. I think this is still true: we should collect some evidence that pipelined operations are either unperformant or overly-expensive in resources before we spend engineering time making a change here.

**Comment by tgeoghegan** [comment]
I don't think this issue is tracking any specific work anymore. There's different experiments and load tests we might consider but I think they are better tracked in specific issues.
