### ISSUE TITLE
Support multiple VDAF verification parameters per task

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#229]
Currently, the `task_vdaf_verify_params` table supports exactly one verify parameter per task. This is because the DAP spec does not yet specify how these parameters might be rotated.

Once the DAP spec specifies how to rotate verification parameters (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/161), we need to do the necessary implementation work to support multiple verification parameters in Janus.

**Comment by divergentdave** [comment]
Based on subsequent updates to specs, we plan to just generate one VDAF verify key before we start accepting reports for a task, distribute it between the aggregators, and use that key for the lifetime of the task.

In order to rotate the VDAF verify key once report processing has begun, we would need some means within the DAP protocol for the aggregators to signal which VDAF verify key they used for each aggregation. Moreover, newly rotated keys would have to be generated through some MPC protocol, so that one rogue aggregator couldn't select the key adversarially to compromise the privacy of a client report it has seen.

**Comment by branlwyd** [comment]
Looking at this issue, I think it should simply be closed. DAP made the decision to rotate these parameters by rotating the task itself; rotation of VDAF verify keys is therefore not an operation we ever need to support.
