### ISSUE TITLE
Produce single Janus binary, container image

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2312]
Currently, we build separate binaries and containers for `janus_aggregator`, `janus_aggregation_job_creator`, `janus_aggregation_job_driver` and `janus_collection_job_driver`. Besides serving HTTP requests, `janus_aggregator` also optionally can do garbage collection.

We should instead build a single binary, named `janus_aggregator`, that can be configured to do any of these five things (serve HTTP, periodically schedule aggregation jobs, consume aggregation jobs, consume collection jobs or collect garbage) based on a subcommand. Correspondingly we would build and distribute a single container image.

To make this easy for existing usage of `janus_aggregator` as a helper, we could rig up the container's entrypoint so that by default, it acts as an HTTP handler (which implements everything needed to act as a DAP helper).

**Comment by tgeoghegan** [comment]
We should go do this soon, while we're in a breaking changes window for Janus 0.7.

**Comment by inahga** [comment]
I think we could take this as a non-breaking change, for the sake of backporting to 0.6.

We can do this by backporting the single binary functionality, but also have the binary parse its own binary name, `argv[0]`, to determine which subcommand to run.

```rust
let bin = std::env::args.collect::<Vec<_>>()[0];
match bin {
     "janus" => { /* behave normally */ },
     "janus_aggregration_job_driver" => { /* behave as if we're aggregation_job_driver */ }
    ...
}
```

We maintain backwards compatibility by having the containers be renamed copies of the main binary that determine functionality by their binary name. This is a similar theory as to how busybox works.

This should simplify our deployment code since we can use the same code for 0.6 and 0.7. Not sure if it's worth the effort though, just throwing the idea out there.

**Comment by inahga** [comment]
> We should instead build a single binary, named janus_aggregator, that can be configured to do any of these five things (serve HTTP, periodically schedule aggregation jobs, consume aggregation jobs, consume collection jobs or collect garbage) based on a subcommand. Correspondingly we would build and distribute a single container image.

FWIW I think we should roll the `janus_cli` into it as well, so we truly only have one binary.

**Comment by divergentdave** [comment]
We can make use of clap's `multicall` flag, and add a subcommand enum around our existing command line parsers.

Bonus: we could build one image with the binary hardlinked under several names, and tag it with all five image names.
