### ISSUE TITLE
Derive client_timestamp_interval from individual `batch_aggregations` instead of `batches`

### ISSUE THREAD

**Issue by inahga** [divviup/janus#2385]
Transactions that insert into `batches` perform poorly because each transaction needs to update the `batches.client_timestamp_interval` column.

We should drop `batches.client_timestamp_interval` and instead calculate the interval by merging shards of the `batch_aggregations` table.

Because `batch_aggregations` is sharded, this should yield fewer serialization errors for aggregation jobs.

(Note that leader aggregation jobs also update the column `outstanding_aggregation_jobs` which is similarly unsharded. The leader may still have performance issues even with this change).

Additional context https://isrg.slack.com/archives/C0167LT4C73/p1703018640025059

**Comment by inahga** [comment]
This is somewhat tricky because our garbage collection logic determines whether a `batches` row is expired by checking the upper end of the `collection_timestamp_interval`. https://github.com/divviup/janus/issues/1467

**Comment by branlwyd** [comment]
> This is somewhat tricky because our garbage collection logic determines whether a `batches` row is expired by checking the upper end of the `collection_timestamp_interval`. #1467

Yep. I think what we want to do is:
1) Update the query in `delete_expired_collection_artifacts` such that the reference to `client_timestmap_interval` in the `batches_to_delete` subquery is based on a join into `batch_aggregations` computing the maximum of the `client_timestamp_interval` across all relevant `batch_aggregations`.
2) Maintain the current GC logic for all other tables, i.e. they are GC'ed if the `batches` row is GC'ed [or based on the `batch_interval` directly for time-interval queries for the `collection_jobs`, `aggregate_share_jobs` tables].

**Comment by divergentdave** [comment]
This change sounds reasonable to me, but I wanted to point out aspect about the current behavior. Tracking `batches.client_timestamp_interval` in one tuple along with `batches.state` means that all transactions will have a consistent view of updates to these columns in a single tuple. In contrast, recomputing summary values from scans may encounter phantom reads, since we're not running at the SERIALIZABLE isolation level, leading to inconsistent views of updates to a `batches` row versus whatever `batch_aggregation` rows happen to be visible.

The possibility of phantom reads is mitigated in two ways: first, we pre-create empty `batch_aggregation` rows when handing an aggregate share job or a collection job, and once we have the full complement of shard rows committed, phantom reads shouldn't be a concern anymore. Second, since the main use of this column is GC visibility conditions, the impact of phantom read anomalies would be collection objects flickering in and out of visibility briefly before they are finally made invisible as time advances.

**Comment by inahga** [comment]
That's a good point, but I think we're fine without any mitigations. While the SQL spec permits phantom read at REPEATABLE READ, [PostgreSQL does not](https://www.postgresql.org/docs/current/transaction-iso.html#TRANSACTION-ISO) (see table 13.1 and second following paragraph).

(FWIW cockroachdb only runs at SERIALIZABLE, so we should be fine there too).

**Comment by divergentdave** [comment]
Ah good point, a phantom read anomaly would be getting two different scan results _in the same transaction_, but that's prevented without much extra work by virtue of reading from a single MVCC snapshot. We can still run into serialization anomalies, particularly in relation to results of scans, but those are harder to describe succinctly.
