### ISSUE TITLE
HPKE keys: explicitly mark one key "primary"

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#239]
At time of writing, the "primary" HPKE config for a task (used for encryption, passed to clients when they request the current HPKE config, prioritized for decryption) is determined as the HPKE config with maximal config ID.

This could be problematic since the HPKE config ID is a `u8`, and so may plausibly wrap around. We should instead explicitly mark one of the HPKE configs as "primary".

**Comment by inahga** [comment]
Do we *need* to determine a primary HPKE key?

We can present a list to the client, and the client can make that decision for themselves, i.e. choose index 0 or choose the key with ciphers that it supports/prefers. The client has to index the response anyways, because we return a list of configs.

We will know which key was used for decryption because its ID is supplied in plaintext along with the encrypted report.

**Comment by inahga** [comment]
This is more or less moot with global HPKE keys support and the key rotator https://github.com/divviup/janus/issues/1641.
