### ISSUE TITLE
Cleaning up after testcontainers

### ISSUE THREAD

**Issue by cjpatton** [divviup/janus#244]
Once in a while I get the following error when attempting to spin up janus in local tests:

```
﻿﻿  2022-06-14T04:31:14.598816Z ERROR testcontainers::core::logs: Failed to find message in stream after comparing 15 lines.
    at /Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.13.0/src/core/logs.rs:83 on ThreadId(1)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EndOfStream(["********************************************************************************", "WARNING: POSTGRES_HOST_AUTH_METHOD has been set to \"trust\". This will allow", "         anyone with access to the Postgres port to access your database without", "         a password, even if POSTGRES_PASSWORD is set. See PostgreSQL", "         documentation about \"trust\":", "         https://www.postgresql.org/docs/current/auth-trust.html", "         In Docker's default configuration, this is effectively any other", "         container on the same system.", "", "         It is not recommended to use POSTGRES_HOST_AUTH_METHOD=trust. Replace", "         it with \"-e POSTGRES_PASSWORD=password\" instead to set a password in", "         \"docker run\".", "********************************************************************************", "initdb: error: could not create directory \"/var/lib/postgresql/data/pg_wal\": No space left on device", "initdb: removing contents of data directory \"/var/lib/postgresql/data\""])', /Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.13.0/src/clients/cli.rs:402:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm wondering how I'm supposed to clean up after running the tests. A few more details:
1. I'm calling `janus_server::aggregator::aggregator_server()` with an ephemeral data store.
2. I'm running a fairly old version while I wait to catch up to the latest version of the spec. Specifically I'm checked out at `54ba8e759e35996a6ea8773aa5f72973d19d4712`.

**Comment by divergentdave** [comment]
It appears that the commit you're using is after the IPv4/IPv6 port number workaround, so that shouldn't be it. I haven't run into this issue myself, but I presume it's more likely that this is hitting an inode limit than a disk space limit.

You mentioned cleaning up, testcontainers can leave behind a running Docker container if the test process is killed. In normal operation, it creates a container without the `--rm`flag, starts it, checks on it with `docker inspect` at various times, retrieves the container's exit code if it exits on its own, or stops and deletes the container if a RAII guard is dropped first. There are no guarantees about Drop implementations getting run, of course, so if we introduced a deadlock into a test, and Ctrl-C'd it, that would leave at least one container running with nothing supervising it. This can be cleaned up with `docker ps`/`docker rm`/`docker system prune`.

**Comment by divergentdave** [comment]
In cases where Docker Desktop stores container filesystems on space-limited virtual disk drives, it's possible our test suite may bump up against container disk space limits, depending on how many parallel tests are in flight with their own database container. This can be addressed by either [allocating more space for Docker](https://docs.docker.com/desktop/mac/space/) or [limiting the parallelism of tests](https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively) with `cargo test -- --test-threads 1`.

**Comment by divergentdave** [comment]
Here's a one-liner to clean up containers after killing a test process.

```bash
docker rm --force $(docker ps --all --quiet --filter=ancestor=postgres:14-alpine)
```
