### ISSUE TITLE
Decide how to handle collection attempts on abandoned collect jobs

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#248]
In some cases (e.g. repeated failures) we will permanently abandon collect jobs. These collect jobs will never complete. However, the collector will have the collect job ID, and can thus request collection of these jobs.

We might consider specifying the "permanent failure" state in the DAP spec; the upside would be an interoperable way for an aggregator to communicate to a collector that a given collect job should be abandoned.

**Comment by tgeoghegan** [comment]
[Relevant paragraph in draft-ietf-ppm-dap-02](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.1-14):

>If obtaining aggregate shares fails, then the leader responds to subsequent HTTP GET requests to the collect job URI with an HTTP error status and a problem document as described in [Section 3.2](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#errors).

Currently, our database stores failed collect jobs with `state = ABANDONED`, so the aggregator can tell that a collect job is unserviceable due to repeated failures when the aggregator services a request to a collect job URI. All the failure modes that have to do with invalid collect requests are detected when an aggregator handles a request to `/collect` (https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.1), so I think all the possible errors here would be because of some server error in either the leader or the helper. In either case, I think HTTP 500 is appropriate there.

Still, we might want to extend the `collect_jobs` table with something like a `failure_reason VARCHAR` column so that we can store a string explaining the failure and then relay that to the client. That string could contain stuff like request IDs or some context specifying which aggregator the failure occurred in which would aid debugging.
