### ISSUE TITLE
Proposed style change for embedded SQL queries

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2562]
Currently, our convention for SQL queries is to use multiline `""` literals, start the query at the beginning of the literal, and indent following lines of the query either to the same column as the opening `"` or further, guided by the syntactic position within the SQL. I suggest that we change our conventions to instead start with a single-line `--` SQL comment, containing the name of the `Transaction` method in which it appears, and then begin the SQL query proper on the following line, left justified to column 0 (and indenting from there based on SQL syntax). This would have the following benefits:

- No need for manual style fixes when making unrelated changes
  - Currently, if rustfmt indents or dedents a `prepare_cached()` call, it won't change the number of spaces within the string literal, since they are semantically meaningful. However, this results in query bodies no longer lining up with the start of the string literal. We have a few cases like this present in the code now.
- Easier to unambiguously identify queries from query logs
- Less pressure on line length in `datastore.rs` and `datastore/tests.rs`
  - Less cases where rustfmt can't format a chain
- Less whitespace in query logs
  - Maybe more headroom before hitting Cloud SQL Query Insights's query length limit (it is unclear if the limit is on actual query length or normalized query length)

This is inspired by a similar trick I picked up somewhere for embedded YAML, wherein string literals start with a `---` document separator, and the indentation-sensitive YAML then follows against the left gutter, just as it would in a separate file.

Alternately, if we don't want to maintain the method names within queries, we could instead start query strings with an empty `--` single-line comment, then make the same indentation change. This would get us all but one of the above benefits.

**Comment by inahga** [comment]
The other idea I had idling in my head was to relocate queries into their own files, then use [`include_bytes!`](https://doc.rust-lang.org/std/macro.include_bytes.html) to substitute the text at compile-time.

The major drawback to this is that we lose locality of query and code. I can accept it since my workflow enables side-by-side editing, but I can't speak for others. I think this satisfies all of the stated problems, and it also lets us more easily pipe queries through a [SQL formatter](https://github.com/darold/pgFormatter).

**Comment by branlwyd** [comment]
Sure, no objections from me.
