### ISSUE TITLE
Clear batch_aggregations.aggregate_share when in state COLLECTED

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2653]
We should set the aggregate_share column to null when updating the state to COLLECTED. At this point, we will have already used the partial aggregate share in computing a full aggregate share, so we won't need it anymore, and in fact we shouldn't use it anymore. This column is currently a leading source of storage consumption with larger VDAFs.

**Comment by branlwyd** [comment]
This is a good idea.

While implementing, we should double-check the behavior of repeated collection of the same batch -- if we aren't caching/reusing the result already, we'll need to begin doing so in order to NULL out `batch_aggregations`.

**Comment by branlwyd** [comment]
> While implementing, we should double-check the behavior of repeated collection of the same batch -- if we aren't caching/reusing the result already, we'll need to begin doing so in order to NULL out `batch_aggregations`.

Based on code inspection:
* The Leader does allow creation of multiple collection jobs targeting the same (batch, aggregation parameter). Currently, it will recompute the aggregate share for each such collection job by reading the relevant `batch_aggregation`s.
* The Helper will accept multiple aggregate share requests for the same (batch, aggregation parameter). Currently, it will recompute the aggregate share for each request by reading the relevant `batch_aggregation`s.

That is, both the Leader & the Helper will need to do something for us to `NULL` out `batch_aggregations` rows. Perhaps the best solution would be to have the Leader & Helper reuse the already-computed result from `collection_jobs` & `aggregate_share_jobs` (respectively).

**Comment by branlwyd** [comment]
Note to self: I should check GC semantics to make sure that we won't GC the `collection_jobs`/`aggregate_share_jobs` we hope to borrow from before the `batch_aggregations` we hope to scrub. I think we're OK but this would be an annoying hole in our implementation strategy if not.

**Comment by branlwyd** [comment]
GC is fine:
* In fixed-size, `collection_jobs` & `aggregate_share_jobs` are GC'ed at the same time as the `batch_aggregations` (i.e. both when the `client_timestamp_interval` of the related batches row is older than the GC horizon).
* In time-interval, `collection_jobs` & `aggregate_share_jobs` are GC'ed when the minimum of the collection interval is beyond the GC horizon; `batch_aggregations` are GC'ed when the minimum of maximum of the batch interval is beyond the GC horizon. That is, `collection_jobs` & `aggregate_share_jobs` are GC'ed before `batch_aggregations`. But this is OK: once the `collection_job`/`aggregate_share_job` is GC'ed, an identical request would not be accepted because it would already be beyond the GC horizon, so we won't lose the ability to handle a non-GC'ed `collection_job`/`aggregate_share_job` due to scrubbing the `batch_aggregations` & then losing the `collection_job`/`aggregate_share_job`.
