### ISSUE TITLE
Fix and reenable task upload counters

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2654]
We deployed accurate per-task metrics using the `task_upload_counters` table and found that it created performance problems for report uploads. We made a hotfix in #2656 that removes the calls to `Transaction::increment_task_upload_counter`. We should diagnose the problem and re-enable the feature. This time, we should make sure to wire up a feature flag/configuration option that would let us disable this without requiring code changes.

---
So it seems these improvements are necessary:
- [ ] Reduce statement count by batching increments.
- [ ] Adjust `fillfactor` to leave per-page space for HOT updates.
- [ ] Lock task stats behind a feature flag so we can turn it off in a pinch if need be.

**Comment by tgeoghegan** [comment]
What we observed is that the `INSERT INTO task_upload_counters ...` query was top of the list in GCP query insights. It's spending all its time waiting to acquire locks. The query in question is:

```
INSERT INTO
  task_upload_counters (task_id,
    ord,
    report_success)
VALUES
  ((
    SELECT
      id
    FROM
      tasks
    WHERE
      task_id = $1), $2, $3)
ON
  CONFLICT (task_id,
    ord) DO
UPDATE
SET
  report_success = task_upload_counters.report_success + $4
```

I guess the issue is that if you have many uploads coming in at the same time for a single task, then they'll all try to write to the same row of `task_upload_counters`, and will lock it, whereas the corresponding writes to `report_uploads` or `report_aggregations` only affect a single row. @divergentdave suggested batching up writes to the task counters (i.e. increment them by 500 or 1,000 at once) so that we do fewer database transactions.

**Comment by divergentdave** [comment]
Each batch of reports will only write to upload counter rows with one particular `ord` value, and all of the counter increments happen in the same transaction as the report insertions. My suggestion was more aimed at reducing the number of statements per transaction, and the number of times we update (and possibly lock) the same tuples.

**Comment by inahga** [comment]
I think @divergentdave is right about heap-only tuple chains becoming too long (thx for the breadcrumb in slack).

Looking at some charts of the incident.
<img width="1775" alt="image" src="https://github.com/divviup/janus/assets/57697428/116294c2-0f34-4e14-b786-bb8c3b7435c9">

In the beginning, HOT updates dominate row updates. At a certain threshold, non-HOT updates become more frequent.

Since this table is so frequently updated (once every 100ms for each aggregator replica), non-HOT updates to a given row are extremely costly since they involve index updates. Indeed, the number of row exclusive locks is coincident with the rate of non-HOT updates.

I'm not sure of the performance characteristics of HOT vacuuming, which is triggered by any statement that affects the row, but I'm guessing it does start to get regressive with massive HOT chains.

I'm not totally clear on what triggers the threshold. It could be load driven but it could also be time driven. I'll try both approaches in load testing to try and get a reproducer.

I think we need to persuade postgres to always prefer HOT updates and lower the cost of in-page vacuuming. This can be controlled with the [`fillfactor` parameter](https://www.postgresql.org/docs/current/sql-createtable.html#RELOPTION-FILLFACTOR).

> My suggestion was more aimed at reducing the number of statements per transaction, and the number of times we update (and possibly lock) the same tuples.

The thing I can't figure out through reading is whether postgresql will actually commit links in the HOT chain that were immediately dead/obsoleted in the same transaction (or real tuples for that matter). I'll have to try it out.

```
1> UPDATE task_upload_counters SET count = count + 1; # New tuple, link old row (0) to 1
2> UPDATE task_upload_counters SET count = count + 1; # New tuple, link 1 to 2
3> UPDATE task_upload_counters SET count = count + 1; # New tuple, link 2 to 3
4> COMMIT;
```
Did I just commit links 0 -> 1 -> 2 -> 3? Or did I commit links 0 -> 3?

**Comment by divergentdave** [comment]
FWIW, my initial incorrect assumption was that lots of HOT updates would effectively create a very long linked list, but I think that's impossible because HOT-updated tuples necessarily must live in the same database page. So, there's a hard limit on linked list length, and pointer chasing within one database page should be very cheap.

Here's the internal documentation on HOT, haven't read through it yet https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/access/heap/README.HOT

The `ctid` system column will likely be useful in inspecting this behavior, as it gives you a tuple's page identifier and index within the page. The `pageinspect` extension will allow low-level access to dead tuples.

**Comment by inahga** [comment]
It does look like multiple increment statements are undesirable, even if in a transaction.

For comparison, here is updates without a transaction (i.e. simulating multiple transactions each INSERTing).
```
postgres=# create table foo ( id bigint, count bigint);
CREATE TABLE
postgres=# insert into foo values (0, 0);
INSERT 0 1
postgres=# SELECT lp, lp_off, lp_len, t_ctid, raw_flags FROM heap_page_items(get_raw_page('foo', 0)), LATERAL heap_tuple_infomask_flags(t_infomask, t_infomask2);
 lp | lp_off | lp_len | t_ctid |      raw_flags
----+--------+--------+--------+---------------------
  1 |   8152 |     40 | (0,1)  | {HEAP_XMAX_INVALID}
(1 row)

postgres=# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=# SELECT lp, lp_off, lp_len, t_ctid, raw_flags FROM heap_page_items(get_raw_page('foo', 0)), LATERAL heap_tuple_infomask_flags(t_infomask, t_infomask2);
 lp | lp_off | lp_len | t_ctid |                                        raw_flags
----+--------+--------+--------+-----------------------------------------------------------------------------------------
  1 |   8152 |     40 | (0,2)  | {HEAP_XMIN_COMMITTED,HEAP_XMAX_COMMITTED,HEAP_HOT_UPDATED}
  2 |   8112 |     40 | (0,3)  | {HEAP_XMIN_COMMITTED,HEAP_XMAX_COMMITTED,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  3 |   8072 |     40 | (0,4)  | {HEAP_XMIN_COMMITTED,HEAP_XMAX_COMMITTED,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  4 |   8032 |     40 | (0,5)  | {HEAP_XMIN_COMMITTED,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  5 |   7992 |     40 | (0,5)  | {HEAP_XMAX_INVALID,HEAP_UPDATED,HEAP_ONLY_TUPLE}
(5 rows)
```
And updates with a transaction.
```
postgres=# create table foo ( id bigint, count bigint);
CREATE TABLE
postgres=# insert into foo values (0, 0);
INSERT 0 1
postgres=# SELECT lp, lp_off, lp_len, t_ctid, raw_flags FROM heap_page_items(get_raw_page('foo', 0)), LATERAL heap_tuple_infomask_flags(t_infomask, t_infomask2);
 lp | lp_off | lp_len | t_ctid |      raw_flags
----+--------+--------+--------+---------------------
  1 |   8152 |     40 | (0,1)  | {HEAP_XMAX_INVALID}
(1 row)

postgres=# begin;
BEGIN
postgres=*# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=*# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=*# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=*# update foo set count = count + 1 where id = 0;
UPDATE 1
postgres=*# commit;
COMMIT
postgres=# SELECT lp, lp_off, lp_len, t_ctid, raw_flags FROM heap_page_items(get_raw_page('foo', 0)), LATERAL heap_tuple_infomask_flags(t_infomask, t_infomask2);
 lp | lp_off | lp_len | t_ctid |                           raw_flags
----+--------+--------+--------+---------------------------------------------------------------
  1 |   8152 |     40 | (0,2)  | {HEAP_XMIN_COMMITTED,HEAP_HOT_UPDATED}
  2 |   8112 |     40 | (0,3)  | {HEAP_COMBOCID,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  3 |   8072 |     40 | (0,4)  | {HEAP_COMBOCID,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  4 |   8032 |     40 | (0,5)  | {HEAP_COMBOCID,HEAP_UPDATED,HEAP_HOT_UPDATED,HEAP_ONLY_TUPLE}
  5 |   7992 |     40 | (0,5)  | {HEAP_XMAX_INVALID,HEAP_UPDATED,HEAP_ONLY_TUPLE}
(5 rows)
```
So we lose out on page space to tuples that are immediately obsoleted in the same transaction. Very interesting. I didn't think you could commit tuples that are DOA.

So it seems these improvements are necessary:
- [ ] Reduce statement count by batching increments.
- [ ] Adjust `fillfactor` to leave per-page space for HOT updates.
- [ ] Lock task stats behind a feature flag so we can turn it off in a pinch if need be.

**Comment by branlwyd** [comment]
Another idea: we could separate the metrics-update work from the report-write work, using a `MetricsBatchWriter` similar to the batched report writer we currently have. This metrics writer would accept metrics (returning immediately), batch them, and write them efficiently as a batch. This would move metrics updates out of the critical path of report uploads.

The downside is that if an aggregator process dies unexpectedly we'll lose the last few seconds of metrics, which will eventually be lost revenue.

I do think we should prioritize continuous load testing in staging. I think all we would need would be a load generator & collector.

**Comment by tgeoghegan** [comment]
> I do think we should prioritize continuous load testing in staging. I think all we would need would be a load generator & collector.

See https://github.com/divviup/janus-ops/issues/1332

**Comment by inahga** [comment]
> Another idea: we could separate the metrics-update work from the report-write work, using a MetricsBatchWriter similar to the batched report writer we currently have. This metrics writer would accept metrics (returning immediately), batch them, and write them efficiently as a batch. This would move metrics updates out of the critical path of report uploads.

I think this turns out trickier than it's worth. This collides with a couple of edge cases:
- We don't know whether a report is for an interval that's already collected until we `validate` the report. So we'd have to increment the `interval_collected` counter in-line with report uploads. n.b. this only affects time interval.
- We don't know whether we can actually increment `report_success` until we insert the report. This is because we rely on a uniqueness constraint to detect duplicate reports.

**Comment by inahga** [comment]
I've not had any success reproducing this issue locally, and I've run out of CPU capacity to push it harder. I've also tried simulating some more prod-like conditions, i.e. multiple tasks, increasing shard count. From my end, HOT-updates continue to dominate the number of updates.

I have not tried fault injection such that other columns besides successful are incremented, but I can't reconcile how that would make a difference. (i.e. I think our load test suite could benefit from some client-side fault injection, I'm punting on that for time concerns).

That being said I feel confident enough in the [solution](https://github.com/divviup/janus/pull/2684), and the ability to turn it off with a feature flag, to continue forward without local reproduction.

**Comment by inahga** [comment]
While this last change is deployed, I'd like to keep this open to explore more optimization.

Currently, there's large latency spikes in uploads, upwards of 600ms-10s 99th percentile spikes. This ostensibly coincides with serialization retries.

I think we ought to take @branlwyd suggestion to decouple metrics and uploads, at least in the same transaction. If the upload transaction has to be retried, which is inevitable regardless of the shard count, it's a lot of work that has to be retried due to INSERTs.

**Comment by inahga** [comment]
I'm happy with the change introduced in https://github.com/divviup/janus/pull/2754, for now. Upload transaction latency looks normal, without large spikes. We also are performing mostly HOT updates with the smaller secondary transaction.

I will check again when we get higher load, but for now I am happy with these results.
