### ISSUE TITLE
Notices sent via the database connection

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#275]
The Postgres protocol allows the backend to send a "notice" message to the frontend at any time, to communicate warnings and other messages regarding query execution or other events. Due to the structure of `deadpool_postgres`, we cannot currently receive these notices. We would need to be able to run or see the output of [Connection::poll_message()](https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Connection.html#method.poll_message) We should do one of the following.

* Extend `deadpool_postgres` with a new option or callback to provide messages/notices over a channel, allow callers to react to messages, or allow callers to take the `Connection` object and customize how it is spawned on an async runtime. Then, we could log contents of notice messages we receive. There is a tangentially related issue, bikeshedder/deadpool#48, which did not receive much activity.
* Determine if we can see the contents of notices in the database's log as well, and determine if this log is accessible through GCP's monitoring services when running on Cloud SQL.
* Survey the possible messages that could be sent in notices, and determine that we don't need access to them.

**Comment by BranLwyd** [comment]
What's the context on this issue? I noticed the `NOTIFY` functionality issue, too, but we don't currently actually use `LISTEN/NOTIFY` in our database design.

I think unless we wanted to use `LISTEN/NOTIFY`, we can ignore this functionality piece. I think this is the expectation of Postgres, too, per [1]: "It is up to the database designer to define the channel names that will be used in a given database and what each one means." That is, notify channels are an application communication channel, rather than a debugging channel.

We might decide to use something like this in the future, but for now I'm OK with a polling strategy for new objects.

[1] https://www.postgresql.org/docs/current/sql-notify.html

**Comment by divergentdave** [comment]
I noticed this while reading through the PostgreSQL docs on its wire protocol. https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.4 I agree we won't need `NOTIFY`, but my concern is about the similarly-named "notice" message type. (see the definitions of NotificationResponse vs. NoticeResponse on that page) These can be sent during normal operation. As an example, there's a statement on this page that says "however, a warning will be issued since a COMMIT or ROLLBACK without a previous BEGIN might represent a mistake".

**Comment by BranLwyd** [comment]
I see, thanks for the clarification -- in that case, I think this bug is a nice-to-have, it seems that the notices might help with debugging but aren't necessary for correct operation.

**Comment by divergentdave** [comment]
I tried out patching deadpool to print these notices, and confirmed I could get the "ROLLBACK without a previous BEGIN" warning. When running the whole test suite, I didn't see any other notices. Between that, and the fact that such warnings should show up in the database's log output, I don't think we need to do anything further here.
