### ISSUE TITLE
`tasks` is missing `updated_at` column

### ISSUE THREAD

**Issue by inahga** [divviup/janus#2819]

**Comment by inahga** [comment]
@tgeoghegan was this intentional in https://github.com/divviup/janus/pull/2079? I was thinking maybe we didn't have `updated_at` because we intended tasks to be fully immutable--but if that were the case I figured we would omit `updated_by` too.

**Comment by tgeoghegan** [comment]
My thinking was that `tasks` rows are immutable, so `updated_at` is unnecessary. The `updated_by` column is still present because we want to record who was responsible for creating a row, and I didn't bother to create distinct `updated_by` and `created_by` columns in any tables.

In any case, since `tasks` is now mutable, we should add an `updated_at` column to `tasks`, and default its value to the creation time.

**Comment by inahga** [comment]
Makes sense, thanks for clarifying!
