### ISSUE TITLE
DB schema migrations

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#30]
We will need to change the database schema over time and so will need to figure out a way to handle versioning, migrations, etc. There should be some product or middleware we can use for this. We can probably make it through early experimental phases by just throwing away databases instead of migrating them, though.

**Comment by BranLwyd** [comment]
I found a couple of potential solutions. These are both free & open-source with a paid support option, and support Postgres:

* [Flyway](https://flywaydb.org)
* [Liquibase](https://www.liquibase.com)

I haven't evaluated these on technical merits, popularity, or anything else.

**Comment by BranLwyd** [comment]
Both of these expect the user to produce "migration scripts", i.e. they do not take a full DB schema and diff it against an existing schema. Flyway works with SQL scripts directly; Liquibase can do this too, but most of the more advanced features (such as rollback) require use of a custom markup language (XML, YAML, JSON are supported). The use of a custom markup language would make it pretty difficult to migrate to a different solution if Liquibase doesn't work out.

Note Liquibase does have a [diff-changelog](https://docs.liquibase.com/commands/diff/diff-changelog.html) command which can produce a changelog based on the diffs between two databases -- but it works on live DBs, rather than schemas, AFAICT.

There are some tools like pgdiff, pgadmin, ... which can produce diffs on schemas, but they don't support CI/CD integration directly, so we'd need to build something.

**Comment by BranLwyd** [comment]
The free version of Flyway does not support "undo", which IMO is disqualifying. (Liquibase's free offering does support undo.) Assuming we want to start with a free option, IMO Liquibase (or something else entirely) is appropriate.

The apparently-most-popular alternative after Liquibase/Flyway appears to be [Bytebase](https://www.bytebase.com). Bytebase appears to be a web application allowing editing & deploying of SQL migration scripts. It also does not appear to have prebuilt CI/CD support. I suspect it's not a good fit for what we hope for.

[Yuniql](https://yuniql.io) is another option. It is effectively a CLI tool which seems to be easy enough to integrate into a CI/CD pipeline. It does use SQL scripts to define the migrations (as opposed to a tool-specific format). However, it appears to be a much less notable project than Liquibase, and it runs on .NET Core which may be slightly more difficult to deploy to our CI/CD pipeline.

**Comment by divergentdave** [comment]
In terms of Rust-language tooling, I think [SeaORM's migration support](https://www.sea-ql.org/SeaORM/docs/migration/writing-migration/#raw-sql) looks particularly promising. We would not use the rest of their ORM features, since we're directly controlling our schema and queries. The `sea-schema` crate it uses is interesting, as it can build its Rust-based database object model from queries against the catalog of a live database.
