### ISSUE TITLE
Garbage-collection of datastore data

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#313]
At time of writing, there is no garbage-collection process which deletes old data in a Janus datastore that is no longer useful. This means that, given a constant level of data ingestion, our data storage will grow linearly over time.

We should devise and implement a policy for deletion of data once it is no longer useful. This should cover all existing tables (or, more generally, all data stored by the Janus system). It will be important to make sure we remain DAP-compliant; to my knowledge the DAP spec is well-designed to allow this kind of cleanup, with one open issue that must be resolved (collect results currently `MUST` be stored until manual deletion by the collector).

**Comment by tgeoghegan** [comment]
Some work in motion that will be relevant to implementing GC:

Candidates for garbage collection will include anything related to an expired task (https://github.com/divviup/janus/issues/610), though we'll have to choose some (configurable?) grace period before an expired task's data is tossed, because I think it's quite reasonable for aggregations on a task to remain available for some time after new reports aren't being accepted anymore.

https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/367 (or a subsequent change to DAP) may introduce `DELETE` calls on resources like aggregate jobs, aggregate shares and collect jobs.
