### ISSUE TITLE
Helper: Apply backpressure when too many aggregation job requests are queued

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#3181]
Aggregation job requests to the helper can be computationally expensive, and the helper has limited control over when requests arrive. We currently don't impose any limit on the number of concurrent requests, or provide any backpressure signal to leaders making aggregation job requests. We could address this by defining a configurable limit on the number of aggregation jobs that can be processed (somewhat similar to `max_concurrent_job_workers` in the aggregation job driver). We could require that a request acquire a semaphore permit before enqueueing its VDAF preparation task on Rayon's queues. If acquiring a semaphore permit fails, we could immediately return a 503 or 429 response.

**Comment by inahga** [comment]
Largely SGTM.

> If acquiring a semaphore permit fails, we could immediately return a 503 or 429 response.

Hmm. If under contention, a naive round-robin load balancer could direct a request to a 503'ing replica while there are other replicas that could service the request.

Which is an operational concern and not really a Janus concern. However, we may want to think about what Janus needs to communicate to a resource-aware load balancer to signal contention. Perhaps a status probe that returns the number of semaphore permits available?

**Comment by branlwyd** [comment]
Once a Janus instance has received a request, I think we should probably queue it up to handle it -- either it will be eventually processed, or it will time out. (This would be a good time to use a LIFO queue, i.e. a stack, to ensure we don't end up just servicing doomed requests.) Notably I think we should do this queueing/waiting as early as possible, before we even read the request body, to reduce the odds of overload.

We can potentially do better at the LB level. I think the ideal is that we'd configure a maximum number of outstanding requests per backend, scaling up as necessary to allow additional concurrent requests to be handled. Unfortunately, I'm not sure our current LB supports this behavior.

**Comment by inahga** [comment]
I think our need for this would be addressed by [DAP shifting to an async request pattern for aggregation jobs.](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/557#issuecomment-2148321051)

Do we still want to consider this for our DAP-09 implementation?

**Comment by branlwyd** [comment]
I think it might still be useful for a high-volume DAP-09 deployment. More to the point, we'll still be running high-volume DAP-09 deployments for the foreseeable future, so I think it's worth keeping open for now.

**Comment by inahga** [comment]
> Once a Janus instance has received a request, I think we should probably queue it up to handle it -- either it will be eventually processed, or it will time out. (This would be a good time to use a LIFO queue, i.e. a stack, to ensure we don't end up just servicing doomed requests.) Notably I think we should do this queueing/waiting as early as possible, before we even read the request body, to reduce the odds of overload.

In discussion in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/564#discussion_r1664745286, it occurs to me that we don't _have_ to do computation in the same process while an aggregation job request is underway. We can queue up work that is serviced by a separate pool of workers (i.e. a helper-side `aggregation_job_driver`), while leaving the connection open.

That'll solve any load balancer problems--work will be distributed based on job driver logic, same as what is done with the leader. (We might have load balancer problems with long-running connections, but that's not a new problem).

That'll also be baby steps towards implementing https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/564.

**Comment by inahga** [comment]
In slack, we've reached some consensus that we should adopt an "internal async" architecture (as mentioned in my last comment).

---

The other proposed solution, internally queuing requests with some bound and rejecting further requests, is still plausible. However, to be maximally efficient, the upstream load balancer needs to be aware of each Janus replica's queues. Otherwise, the load balancer may round-robin to a replica that is 429'ing, even though there may be other replicas able to service. At a QPS that nears the limits of the overall system, this can lead to excessive retries.

I have been unsuccessful in finding a FOSS load balancer that can be taught to monitor internal queues directly, and make load balancer decisions based on the queue size (i.e. least queued replica).

We _could_ make queue depth a function of the backend healthcheck, i.e. a full replica can start to fail its `/healthz` check. Or the load balancer can be taught to scrape some other `/queue_ready` endpoint and take the load balancer out of the pool if the `/queue_ready` endpoint fails.

That, coupled with a Least Outstanding Requests or Least Active Connections load balancing algorithm, could get us 80% of the way there.

There are still a few problems with this approach:
- LOR/LAC algorithms are... flaky. One problem is that a malfunctioning replica that immediately and errantly instantaneously serves requests (i.e. 500 internal server), is heavily weighted compared to perfectly fine replicas.
- There still lacks overall backpressure. In scenarios where the system needs to scale up, this can lead to scaled-down replicas _still_ becoming overloaded while autoscaling kicks in. A load balancer would need to reroute active connections in the presence of scale-up, but I don't believe in-flight HTTP requests can be effectively rerouted without terminating the connection and having the requestor try again.

---

So, internal async does check a lot of these boxes.

To be clear, internal async changes the aggregate init/continue handles to do roughly the following:
```rust
let existing_job = database.get_queued_aggregation_job(aggregation_job_id);

let job = match existing_job {
    Some(job) => job,
    None => {
        // Do some basic, cheap, checks on the aggregation job request, i.e. make sure it's well-formed.
        if !is_valid(aggregation_job_request) {
            return Err(InvalidRequest);
        } else {
            database.enqueue_new_aggregation_job(aggregation_job_request);
        }
    }
}

// Simple polling strategy, but implementations *could* do their own non-polling design, e.g. postgres LISTEN/NOTIFY.
let deadline = Time::now().add(SOME_REASONABLE_TIMEOUT);
loop {
    let job_response = database.check_if_aggregation_job_is_ready(job);

    if job_response.is_ready() {
        return Ok(job_response)
    }

    if Time::now() > deadline {
        return Err(Timeout);
    }
    sleep(SOME_POLLING_INTERVAL);
}
```

Benefits:
- Autoscaling pressure is moved to the aggregation job driver. The aggregation job driver can be easily taught to only pick up what it can chew from the queue. The corresponding CPU usage can be used to trigger autoscaling.
- No load balancer changes or special considerations required whatsoever.
- Assuming a properly tuned aggregation job driver, available resources will always be efficiently allocated, i.e. no request will be routed to a replica that can't handle it. (This should yield fewer replicas needed for the same target QPS).
- Outstanding requests are durably queued. On retry, we can "join" the existing in-flight aggregation job rather than reprocessing the aggregation job, which saves CPU.
- The current aggregation job transaction is fairly long-lived, which can starve out `/hpke_configs` and `/aggregate_share` requests that need to contend for database connection slot access. A shorter aggregation job transaction would ameliorate this. Related: https://github.com/divviup/janus-ops/issues/1592. 

Drawbacks:
- Fairly complicated body of Janus code needs to be introduced, along with feature flag(s) whose behavior might get complex.
- Increased database load, 2-3x more transactions being run, and increased I/O by persisting aggregation job bodies.
- Lots of polling needs to be done, between polling for aggregation job readiness and driver-side polling for ready aggregation jobs. We may wish to make use of postgres LISTEN/NOTIFY to cut down on polling.
- BYOH deployment may become complicated. We'd want to let the aggregation-job-driver run in-process with the aggregator, which... sucks to keep having to bundle processes together...

**Comment by branlwyd** [comment]
Other than complexity, I'm most concerned about the additional database load. I definitely think we want some kind of notification system to avoid introducing additional latency (and DB load) via polling. Since this is being implemented primarily to address scaling issues, I'm also concerned this shifts the scaling issues to the helper-aggregation-job-driver process -- requests that are waiting on an underprovisioned pool of helper-aggregation-job-drivers will time out just the same as if they are waiting on the computation to be completed inline.

I would suggest we start with a queue and/or simply responding with a backoff response when a request reaches an overloaded Helper -- I think this could be implemented quickly, and would help even if we eventually implement async processing (waiting for the computation, loading it, and sending it over the wire are not free even if the computation is done in a separate process).

**Comment by inahga** [comment]
> I definitely think we want some kind of notification system to avoid introducing additional latency (and DB load) via polling.

Yes, I think [LISTEN/NOTIFY](https://www.postgresql.org/docs/current/sql-notify.html) is the best tool available. Notifications do not have guaranteed delivery (i.e. transient network problem could result in dropped notification), so we would want to have polling as a fallback.

> Since this is being implemented primarily to address scaling issues, I'm also concerned this shifts the scaling issues to the helper-aggregation-job-driver process -- requests that are waiting on an underprovisioned pool of helper-aggregation-job-drivers will time out just the same as if they are waiting on the computation to be completed inline.

Very true, but because the requests are queued durably, we don't need to do VDAF prep for each incoming request. So we should reach equilibrium much faster--instead of each retry needing to do VDAF prep, each retry instead does the much cheaper checks on the queue status and rejoins waiting for the "done" message. This would still need some experimental validation though.

> I would suggest we start with a queue and/or simply responding with a backoff response when a request reaches an overloaded Helper -- I think this could be implemented quickly, and would help even if we eventually implement async processing (waiting for the computation, loading it, and sending it over the wire are not free even if the computation is done in a separate process).

We can try it, you're right it's an easier set of changes. I think the things to check for would be whether the volume of retries gets out of hand (at least 429'd retries are substantially cheaper though), and whether we need to inflate our replica count to reach the target QPS.

**Comment by branlwyd** [comment]
Agreed with most of your points, but IIUC:

> Very true, but because the requests are queued durably, we don't need to do VDAF prep for each incoming request. So we should reach equilibrium much faster--instead of each retry needing to do VDAF prep, each retry instead does the much cheaper checks on the queue status and rejoins waiting for the "done" message. This would still need some experimental validation though.

With a queue/backoff-response implementation, we would reject most requests before we perform VDAF preparation. While this wouldn't reduce work in every case (we might start processing, do VDAF prep, then timeout afterwards), I think it would still be a significant win. Especially if we queue requests into a LIFO queue, most requests that we process will be "fresh" enough that we should (hopefully) succeed at processing them if we start processing them.

**Comment by inahga** [comment]
That is true. Very plausible, I'll give it a try.
