### ISSUE TITLE
janus_cli: kube uses rustls rather than OpenSSL even in debug builds

### ISSUE THREAD

**Issue by BranLwyd** [divviup/janus#327]
The intended behavior is that debug builds will use OpenSSL, while release builds will use rustls. This is to work around https://github.com/kube-rs/kube-rs/issues/153 -- rustls currently can't connect to a Kubernetes cluster through an IP address. The linked issue does not affect "in-cluster" usage, so using rustls for release builds is acceptable.

This worked at time of commit in #314 (should be double-checked), we can bisect from there to find where the breakage occured. Until this issue is resolved, local users of `janus_cli` need to modify the `janus_server/Cargo.toml` to switch the default feature list from `"kube-rustls"` to `"kube-openssl"`.

**Comment by BranLwyd** [comment]
(argh, the issue title was backwards)

**Comment by divergentdave** [comment]
I checked out 7beee2adbe66aabba47ac3665b91e9c209f18882, ran some debug builds for both the single binary target and the whole workspace, and the rustc invocations all include `--cfg 'feature="kube-rustls"'` when building targets in `janus_server`. (The same is true at the tip of main)

I don't think that we can get anything from `default-features = false` in `janus_server`'s dev-dependency on itself, because (a) the set of features that are enabled for a crate is the union of all features required by its dependents, so we would be taking the union of the default feature set, `["kube-rustls"]` with `["kube-openssl", "test-util"]`, and (b) development dependencies are only considered when building tests, examples and benchmarks, not binary targets, and the choice of `release` or `dev` profile is orthogonal to development dependencies.

I think it would make sense to drop `kube-openssl` from the self-dev-dependency, and document that when using Kind, the tool should be run with `cargo run --bin janus_cli --no-default-features --features kube-openssl -- <SUBCOMMAND> ...`.
