### ISSUE TITLE
Consider specifying locking clause on "acquire incomplete {aggregation,collect} jobs" datastore operations

### ISSUE THREAD

**Issue by BranLwyd** [divviup/janus#358]
Currently, the `acquire_incomplete_{aggregation,collect}_jobs` operations do not specify any locking clause on their inner `SELECT` statements.

I think we could reduce DB contention (i.e. transaction retries) by specifying a locking clause as described in the [PostgreSQL manual](https://www.postgresql.org/docs/current/sql-select.html). At a glance I think the clause we want would be `FOR UPDATE SKIP LOCKED`.

**Comment by divergentdave** [comment]
Unfortunately, I don't think `FOR UPDATE SKIP LOCKED` will give us a performance win so long as we use the `SERIALIZABLE` transaction isolation level. Concurrent job acquisition transactions will unavoidably take conflicting predicate locks on the same part of the job table, even if we try to use explicit row locking to make them return disjoint result sets. The predicate locks will cover the whole range of rows considered, which would be the same no matter what `SKIP LOCKED` does.

I found a [blog post from the author of the `SKIP LOCKED` patch, on the topic of `SERIALIZABLE`](https://write-skew.blogspot.com/2018/05/serializable-in-postgresql-11-and-beyond.html) and it says "the rows that you skip are still predicate-locked, so create conflicts among all the competing transactions. ... This forces a choice between SERIALIZABLE and SKIP LOCKED, not because the features exclude each other but because the resulting performance is terrible."

**Comment by BranLwyd** [comment]
Thanks -- that's consistent with my initial experiments here, which (IIRC) specified `FOR UPDATE` but not `SKIP LOCKED`. I saw that, even with `FOR UPDATE` locking, concurrent transactions would acquire the same jobs & then receive a serialization failure on commit, forcing a retry.

I think we'll probably be OK here since the acquire-job queries acquire all of the jobs that the driver can handle in one transaction, reducing the number of transactions that may be running concurrently. This may lead us to want fewer, larger driver jobs, however, to increase the "batch factor."
