### ISSUE TITLE
Audit `tracing` spans for large or secret objects

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#392]
There's some places where we include an entire `Task` structure in tracing spans, which can yield rather large messages. Additionally, some of those objects may contain secret values like HPKE private keys, which we never, ever want to log. We should audit our tracing spans to ensure that no values that are too large or sensitive get logged.

**Comment by tgeoghegan** [comment]
It would be nice if there was some way to tag or taint structs that we know to contain secrets (like `HpkePrivateKey`) so that they are unloggable. Perhaps we can provide [`tracing::Value`](https://docs.rs/tracing/latest/tracing/trait.Value.html) implementations that panic?

**Comment by divergentdave** [comment]
The instrument macro defaults to recording arguments with `tracing::field::Value`, with a fallback to `std::fmt::Debug`, and options to use `std::fmt::Display` instead. The simplest solution would be to customize the Debug and Display implementations for any secret struct, so that they are opaque when printed. Implementing `Value` on `HpkePrivateKey` would not have any effect on how `Task` gets recorded in a span, as `Task` is recorded as a string, using the Debug fallback, and will not touch `Value::record()`. Moreover, `Value` is a sealed trait, so we can't implement it, and I don't think tracing supports compound objects in fields.

**Comment by divergentdave** [comment]
Should we exclude `CollectReq.agg_param` from logging, in anticipation of Poplar1? It could include an ASCII-encoded aggregate result, which may make it sensitive enough to exclude.

**Comment by branlwyd** [comment]
I'm OK excluding it right now:
(a) prio3 doesn't use agg param at all, so we don't lose any logging usefulness currently.
(b) IMO an aggregate result is sensitive enough that we probably don't want to log it
(c) if later VDAFs have an aggregation parameter that is both non-trivial & non-sensitive & we decide we want to log them, we can always change our logging strategy at that point.

**Comment by divergentdave** [comment]
Our log messages look better now, closing this out.
