### ISSUE TITLE
Alternate strategy for containers in integration tests

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#412]
Currently, we run a Docker build from build.rs in two crates, save the resulting container, include it in test binaries via `include_bytes!()`, and load and run that container as part of the test. This has some build time, disk space, and developer experience downsides. It succeeds in tightly binding all components of the tests to the current state of the codebase.

Here's an alternative strategy we should evaluate: Currently, we only use these dynamically built containers during integration tests. Cargo compiles and provides paths to each binary target when compiling integration tests. Instead of performing a separate containerized cargo build during build.rs execution, we could instead rely on binaries built on the host by the same cargo invocation, and only package those binaries into Docker containers at runtime, immediately before then executing that container as part of the test. (i.e., ADD the binary from the host, rather than doing RUN cargo build in the container) This would reduce redundant work, shorten the build pipeline, take large binary blobs out of the compiler, and still ensure that container-based tests are using up-to-date binaries. We would have to rely on host binaries being ABI-compatible with the container's OS, but currently that should work when the host is any Linux distribution, as we only dynamically link to libc et. al. We would have to create and maintain separate Dockerfiles (or templates), different from those Dockerfiles we use to create external-facing artifacts.

**Comment by branlwyd** [comment]
I was thinking about embedding the host-built binary into the image, but I couldn't find a good way to reference the binary outside of an integration test (where the [`CARGO_BIN_EXE_foo` environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) would work). More critically, even for integration tests, this only works if the test is in the same package as the binary -- the `CARGO_BIN_EXE` variables seem to be set only for in-package binaries. Since we want to use the test images across multiple packages, I think this approach won't work for all the cases we care about.

We could try something hacky based on looking up `CARGO_TARGET_DIR`, building the expected binary path ourselves (eg concatenating something like `debug/interop_test_aggregator`), and hoping that the binary was actually built & is fresh. This would work for unmodified `cargo test` (I think? Rust might allow enough parallelism in build steps that we could be building the binary at the same time as attempting to build the container image) but many other invocations would end up not building the binaries & thus either wouldn't work or would use a previously-built binary. (and it'd be hard to automatically fall back to doing the in-container build when needed, since we don't know until test runtime whether the binary is available, and in general we can't be sure it's fresh)

Is there another way to reference binaries I haven't considered?

As you note, this also locks us to using developer workstations that are ABI-compatible with the container OS, which implies we either drop non-Linux developers (I already know of one MacOS user who regularly compiles Janus), or we maintain a set of Dockerfiles to use based on the host (and maybe fall back to the "in-container build" process if we encounter a host we think is incompatible?). This wouldn't make the approach infeasible, just something we'd need to account for if we took this approach.
