### ISSUE TITLE
Re-enable Daphne integration tests once DAP-02 implementation is complete

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#493]
This is done by re-enabling the `daphne` feature on the `integration_tests` package. Reference #491 as the PR which disabled these tests.

This issue should also track any other incidental technical work that needs to occur to make the integration test work with the latest version of Daphne, once we try re-enabling it.

**Comment by divergentdave** [comment]
This is blocked on cloudflare/daphne#100.

**Comment by divergentdave** [comment]
#656 removed our Daphne dependency and the `daphne` feature from `integration_tests/Cargo.toml` in order to unstick our dependency resolution. Before we re-enable this integration test, we'll need to re-add the feature and dependencies, and I think Daphne will need to update to `hpke 0.10.0` as well (I'll open an issue regarding this).

**Comment by tgeoghegan** [comment]
I think we have long since re-enabled Daphne tests for DAP-02, and then turned them back off for DAP-04, and we'll track further integration testing elsewhere.
