### ISSUE TITLE
Partitioning/sharding of data

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#647]
Now that we're starting to think about deleting data, we may want to consider schema changes to support efficient deletion. Doing a naive cascading delete of a task and all its associated data could be expensive, as it would require a long-running read-write query, broad predicate locks, and thus contention with other concurrent transactions.

Application-level sharding and Postgres's [declarative partitioning](https://www.postgresql.org/docs/current/ddl-partitioning.html) would both provide a means to do cheap deletes of data by deleting tables. Application-level sharding is naturally more high-touch, while declarative partitioning imposes some limitations that would affect indexes in our schema.

An important upstream product question that will affect our choices is whether we will impose a maximum lifetime on DAP tasks. This would admit simpler sharding schemes, but it would force clients and collectors to automatically update task parameters, and it may be unacceptable if we wish to integrate with another aggregator that allows tasks without expiration dates by their policy.

One key restriction in Postgres's declarative partitioning feature is that UNIQUE/PRIMARY KEY constraints on any partitioned table must include all columns that are part of the partition key. The indexes that back these constraints only cover one partition of the table, thus they can only enforce uniqueness within the scope of the subset of partition key values it could see. If we were to partition by task_id on most tables, for example, this would require changing from `PRIMARY KEY (id)` to `PRIMARY KEY (task_id, id)`. Our various autoincrementing ID columns would no longer be unique across the whole database, but only unique within the context of one task. (They would also be unique within the context of one partition, but that distinction isn't important)

Depending on the expected lifetime of tasks, we may either want to shard everything but `tasks` by their numeric `task_id` column, or shard some tables by `task_id` and others by both `task_id` and timestamps. Note that `report_aggregations` currently does not include either of these, so we will likely want to denormalize at least `task_id` into it, so that we can partition it. (as it is one of our largest tables by tuple count)

As a hybrid option, we could also combine application-level sharding and declarative partitioning by adding some "partition ID" to each task, adding that ID to other tables, and using declarative partitioning on the column. This would give us greater control over which tasks are stored together, for example, if we chose the partition ID based on task expiration, and we had a variety of task lifetime lengths. If such heuristics wouldn't be useful, then this would be inferior to just partitioning on `task_id`.

Note that if we were to shard `client_reports` by timestamp, our queries checking for ReportID uniqueness would have to fan out across multiple partitions for different time ranges. If we get to the point where we can drop reports of already-aggregated/already-abandoned/past-deadline client reports, we may want to split `client_reports` into two tables, one for ReportID storage and one for the rest, but I think that's a secondary concern for now.

**Comment by divergentdave** [comment]
Google Cloud SQL supports the [`pg_partman`](https://github.com/pgpartman/pg_partman) extension.

**Comment by branlwyd** [comment]
For data-deletion specifically, I think we should investigate a solution based on incremental deletion of data (likely based on implementing "tombstoning" instead of deletion, to allow rows to be logically deleted without requiring a large cascading deletion -- see #1145), before we look to partitioning the database. It looks like this declarative partitioning scheme does not

I think that our data-deletion logic is likely too complicated to map cleanly to partition management. For example, we currently keep aggregation jobs around until all related reports are ready for deletion (because otherwise these reports might end up being aggregated again), and keep reports around until all related aggregations are deleted; this means that if a very old report that is grouped into an aggregation job with a more recent report, the older report will not be GC'ed until the recent report is ready for GC. A naive partitioning scheme would need to account for this by keeping the older report's partition around until every report in the the partition is ready to be GC'ed.

However, using partitioned tables may be helpful to meet performance goals -- if we partitioned by task, for example, I suppose each task would get its own independent indexes.

[also, off-topic but to avoid confusion, Postgres' partitioning implementation is "just" partitioning a table into several subtables to allow table-based operations to be taken on those subtables; it does not provide e.g. multi-process horizontal scalability that would be necessary for a partitioning scheme to solve scalability issues.]

**Comment by branlwyd** [comment]
GC is efficient enough, and if we scale far enough that GC becomes problematic again, we will likely investigate a horizontal sharding solution.
