### ISSUE TITLE
Consider moving job queues out of Postgres

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#891]
I've got a thought in the back of my head that we may want to move our job queues out of Postgres, and into a different durable store that can handle queue semantics more efficiently. Previously, we found that we cannot profitably use `FOR UPDATE SKIP LOCKED` within transactions with `SERIALIZABLE` isolation level. Our task acquisition queries have proven difficult to write efficiently. Scaling up queue-processing components may require sharding which tasks get acquired to avoid contention upon task acquisition.

If we made an architectural change to use a service like Google Pub/Sub, Kafka, etc. for job queues, then driver components could poll the relevant queues for available jobs, and benefit from the queue service's different approach to concurrency control. On the other hand, we would need to have components push jobs to queues, and I have not though through the logic required to determine whether a particular job is ready to be queued. Our job acquisition queries currently encode some DAP logic (i.e. collect jobs are only ready if every contributing aggregation job is done), and we would need to consider equivalent criteria to decide when to push jobs on the queue. (Additionally, we would need to handle cases where a DB transaction updates a job so it's ready, but the subsequent request to push a job on the queue fails, perhaps with another component monitoring the database for stuck jobs.)

As we characterize how Janus scales, this might be a useful approach, but it does add significant complexity. For now, I think this might be worth keeping in mind.

**Comment by branlwyd** [comment]
Other than architectural simplicity, the main reason we haven't done this work is because it is challenging to determine exactly when the state transitions occur. This might be especially challenging if things change across different versions of DAP.

Another reason is that we lose transactionality in updating the storage database vs the job state. Every state of every job would need to be able to handle the case that its work has already been done, and move forward to the next state, to avoid stuckness.

**Comment by branlwyd** [comment]
I think we won't implement this: we can meet our current scalability goals without doing this; if our scalability goals grow larger, we would investigate horizontal sharding of the existing system before this.
