### ISSUE TITLE
Store an explicit connection between reports and batches for time interval tasks

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#964]
Currently, we consider a client report to be a member of a batch in a time interval task based on its timestamp being contained in the batch interval. For fixed size tasks, client reports get associated with a batch by the aggregation job creator, and this is recorded by creating rows in `outstanding_batches`,` aggregation_jobs`, and `report_aggregations`. (the `outstanding_batches` row goes away some time after a `collect_jobs` row has been created with the same batch ID) Thus, batch membership is implicit in the presence of a `client_reports` row for time interval tasks, while it's explicit in `report_aggregations` rows for fixed size tasks.

As a result, time interval report uploads have to do checks for collect jobs in order to freeze batches for anti-replay protection, and collect jobs have to count reports by joining the client_reports table to check batch size constraints. This has negative performance impacts, both in terms of the work done while handling `/upload`, and through high transaction conflict rates. These code paths also include queries that often use too-large GiST index scans, due to query planner limitations (see #729).

I think we should consider redesigning how time interval batches are handled, so that we explicitly assign reports to a batch during the aggregation flow, record that in the database, and only rely on that information when looking up reports and their partial aggregates during the collect flow. This will let us move that component of anti-replay protections out of `/upload`.

To prove out this direction, we should first compare Janus's performance on time interval tasks and fixed size tasks, as it does something similar already. If this direction is promising, then we'll have to design out how it would work, including what to store (collector-provided batch interval or minimum size batch interval? serialized `BatchID` or `tsrange`?), where to store it (`client_reports` column? `report_aggregations` + `aggregation_jobs` like fixed size tasks?), and what changes to make to the aggregation job and collect job state machines (note that for Poplar1, we'd need collect jobs to have a state where they don't block integration of reports into a batch, since the collect job must come first).

**Comment by branlwyd** [comment]
A few thoughts on this direction:

> what to store (collector-provided batch interval or minimum size batch interval? serialized BatchID or tsrange?)

I think we would have to store a minimum-size batch interval: otherwise, I think we can't begin aggregation until the collector sends a collect request defining the appropriate interval. (Compare fixed-size behavior, which assign batch ID at time of aggregation job creation.) We will still need to be able to service collect requests by combining multiple minimum-size batch intervals.

Since we need to be able to translate from our explicit batch representation back to the interval it represents, I think using an explicit `BatchID` would introduce a translation layer that would not be needed if we used a serialized `TSRANGE`, so for now I'm leaning towards adding a `TSRANGE` (or just client report timestamp?) to `report_aggregations`.


> where to store it (client_reports column? report_aggregations + aggregation_jobs like fixed size tasks?)

`client_reports` probably isn't appropriate as part of the goal of this work is to reduce contention on `client_reports` -- so we want to put the new identifier somewhere else.

I think `report_aggregations` is the appropriate place.

**Comment by branlwyd** [comment]
> As a result, time interval report uploads have to do checks for collect jobs in order to freeze batches for anti-replay protection,

This is true, but (a) this hasn't created a performance problem and (b) we could drop this entirely without affecting correctness (since the batch's state would prevent this report from ever joining an aggregation job), which would have the same effect as the suggestion to join the report to a batch only during aggregation (i.e. the report upload would succeed, but we would never aggregate it).

> and collect jobs have to count reports by joining the client_reports table to check batch size constraints.

This is no longer true -- we now rely on the report count in the batch metadata.

For the above reasons, closing this.
