### ISSUE TITLE
Reuse database server for ephemeral datastores

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#999]
We could probably save a lot of per-test setup and teardown time if we reused the same Docker container for multiple parallel tests, and instead isolated the tests from each other with different databases. Extensions and enum types both get created per-database, so our whole schema file should go through fine. We don't read from the system catalog or qualify any relation names with databases or schemas, so everything else should work transparently.

The container needs to be torn down explicitly by `testcontainers` on drop, so we can't just leak the container. Holding a static `RwLock<Weak<Container>>` and sticking corresponding `Arc<Container>`s inside the ephemeral datastore handle would resolve this.

**Comment by branlwyd** [comment]
Sharing the DB containers is a good idea.

Unfortunately, `Container` isn't `Send` or `Sync`, so the `RwLock` idea won't work directly (since static variables must be `Send` & `Sync`). However, that doesn't sink the idea: users of the ephemeral database don't actually need a reference to the `Container`, only (a) the connection information and (b) to ensure that the `Container` isn't dropped while it is in use.

So an approach that would work would be:
* When we need to start a container, start a thread which starts the container then waits to be signaled for shutdown.
* Create a type called something like `EphemeralDatabase`. On creation, this type starts a container-management thread. It keeps the required information to generate connection strings, as well as enough to signal the container-management thread for shutdown. (this will be slightly tricky: we'll need to do the appropriate synchronization to make sure the container actually starts before creation of `EphemeralDatabase` returns) Arrange that dropping an `EphemeralDatabase` signals the container-management thread to halt (then, optionally, waits for container shutdown to be complete via additional synchronization).
* Keep a `Mutex<Weak<EphemeralDatabase>>` (or `RwLock`, but IMO test code doesn't need this level of optimization) around as per your original suggestion.

FWIW, completely unscientifically, the pre-change stats on my machine from one (1) run:
```
$ cargo test -p janus_aggregator --lib -- 'datastore::'
test result: ok. 37 passed; 0 failed; 0 ignored; 0 measured; 71 filtered out; finished in 26.75s
```

**Comment by branlwyd** [comment]
Nerd-sniped by a concurrency/synchronization problem.

**Comment by branlwyd** [comment]
Initial results look promising:
```
$ cargo test -p janus_aggregator --lib -- 'datastore::'
test result: ok. 37 passed; 0 failed; 0 ignored; 0 measured; 71 filtered out; finished in 12.57s
```

(PR still in-progress, resource cleanups/documentation needed)
